### ISSUE TITLE
Unimake not downloading usvfs repository (probably user error)

### ISSUE THREAD

**Issue by AnyOldName3** [TanninOne/modorganizer-umbrella#11]
I'm attempting to build Mod Organizer with the unimake script, and have got to the point where it outputs the following:
(Sorry for long blocks of stuff, but there aren't spoiler tags here...)

```
C:\ModOrganizerDev>unimake.py
2016-01-08 17:50:48,358 building dependency graph
2016-01-08 17:50:48,377 processing tasks
2016-01-08 17:50:48,377 run task "cmake usvfs"
2016-01-08 17:50:48,377 source path not known for usvfs, are you missing a matching retrieval script?
2016-01-08 17:50:48,377 task cmake usvfs failed
```

or, if I reclone this repository so as to start from scratch:

```
C:\ModOrganizerDev>unimake.py
Collecting decorator
  Using cached decorator-4.0.6-py2.py3-none-any.whl
Installing collected packages: decorator
Successfully installed decorator-4.0.6
adding changesets
adding manifests
adding file changes
added 2081 changesets with 11325 changes to 1685 files
updating to branch default
1512 files updated, 0 files merged, 0 files removed, 0 files unresolved

processing download
File not yet downloaded: .\downloads\udis86-1.7.2.tar.gz
Downloading http://downloads.sourceforge.net/project/udis86/udis86/1.7/udis86-1.7.2.tar.gz to .\downloads\udis86-1.7.2.tar.gz
Downloading [==================================================] 100%
Extracting http://downloads.sourceforge.net/project/udis86/udis86/1.7/udis86-1.7.2.tar.gz
Extracting [                                                  ] 0%%

processing download
File not yet downloaded: .\downloads\win_flex_bison-latest.zip
Downloading http://downloads.sourceforge.net/project/winflexbison/win_flex_bison-latest.zip to .\downloads\win_flex_bison-latest.zip
Downloading [==================================================] 100%
Extracting http://downloads.sourceforge.net/project/winflexbison/win_flex_bison-latest.zip
Extracting [                                                  ] 0%%

processing download
File not yet downloaded: .\downloads\7z920.tar.bz2
Downloading http://www.7-zip.org/a/7z920.tar.bz2 to .\downloads\7z920.tar.bz2
Downloading [==================================================] 100%
Extracting http://www.7-zip.org/a/7z920.tar.bz2
Extracting [                                                  ] 0%%

source path not known for usvfs, are you missing a matching retrieval script?
task cmake usvfs failed
```

I _think_ I've got all the dependencies now. I've have the following installed and on my path:
- MSYSGit
- Cmake
- Python 2.7
- Decorator
- Visual Studio 2013 and 2015
- 7zip
- TortoiseSVN (with shell extension)
- TortoiseHG
- Strawberry Perl
- Ruby

It is my understanding that if I have all these things on my path, and clone this repository into a folder and run unimake.py it should build the entirety of Mod Organizer, using the latest commits to the development branch (new vfs, I think). However, when I _do_ run it, it tries to run cmake for usvfs (as shown above) without actually downloading the source first.

If I'm just using the script incorrectly, then I'd be glad to be pointed in the right direction (and explain exactly why I misunderstood whatever I may have done so the documentation can be adjusted), and I have a little python experience, so may be able to help debugging if it's actually the script that's misbehaving.

**Comment by iulianov** [comment]
I have a pull request (#10) open that should fix this issue. As stated in the request I still do not have a completely working project but I am able to get further. 

I do not think that this is user error unless more manual dependencies were added when usvfs was exposed on github. I had a working build as of 4-5 weeks ago(although it also had to have custom changes).

Unless, like you said there are some requirements we do not know about, you will still get errors after that and will need to make more changes to the build scripts(something I am trying to do now).

**Comment by AnyOldName3** [comment]
It's definitely getting further after swapping in your version of that file. I'd second that pull request.

**Comment by AnyOldName3** [comment]
I've now got to the point where the updated script fails. This should probably go in its own issue, but while the thing I'm commenting on hasn't been merged yet, I'm not sure that's the best idea...

Anyway, the new error output is this:

```
2016-01-08 19:09:11,957 run task "retrieve qt5.git"
2016-01-08 19:09:11,957 Task retrieve qt5.git failed: argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "C:\ModOrganizerDev\unimake.py", line 239, in <module>
    main()
  File "C:\ModOrganizerDev\unimake.py", line 216, in main
    if task.process(progress):
  File "C:\ModOrganizerDev\unibuild\modules\git.py", line 100, in process
    env=config["__environment"])
  File "C:\Python27\lib\subprocess.py", line 710, in __init__
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 913, in _execute_child
    args = list2cmdline(args)
  File "C:\Python27\lib\subprocess.py", line 616, in list2cmdline
    needquote = (" " in arg) or ("\t" in arg) or not arg
TypeError: argument of type 'NoneType' is not iterable
```

Additionally, I had to run the script a couple of times to get zlib to download, but I think that wasn't an issue with the script, but instead with either my network or their site.

**Comment by iulianov** [comment]
The zlib issue does sound like network/site problems since mine downloaded the first time.

As for the retrieve qt5 task can you make sure that you have the path to git inside $PATH$ (my build worked fine until it hit the "run init qt repository" task where it required more changes that I have not pushed to my branch yet)
Also make sure that if you have cygwin in your path that it is at the very end since if the build system finds the cygwin git you will have yet another error due to file paths being different.

Edit: I think your second issue might still be an indication of something not right with your environment but try changing line 616 in subprocess.py to read:
`needquote = not arg or (" " in arg) or ("\t" in arg)`
(when using or inside conditionals its always best to put the worst case first)
You will probably get another error but that one might be more informative.
Edit2: thinking about it some more the whole needquote might be better placed inside a full if-else statement since if arg is None then you might not want to quote it. This might be a case where Tannin should chime in to make sure that the case of arg==None and needquote==True makes sense.

**Comment by AnyOldName3** [comment]
I thought I had git on my path, but apparently I didn't... I'll just fix that.

I only have MSYSGit, and not cygwin, so the other issue shouldn't present itself.

**Comment by AnyOldName3** [comment]
Yep, with git on my path I'm now failing at the same point as you.

```
2016-01-08 19:53:44,563 run task "run init qt repository"
2016-01-08 19:53:44,565 Task run init qt repository failed: 'NoneType' object is not callable
Traceback (most recent call last):
  File "C:\ModOrganizerDev\unimake.py", line 239, in <module>
    main()
  File "C:\ModOrganizerDev\unimake.py", line 216, in main
    if task.process(progress):
  File "C:\ModOrganizerDev\unibuild\modules\build.py", line 253, in process
    if self.__environment() is not None
  File "C:\ModOrganizerDev\unibuild\utility\lazy.py", line 84, in __call__
    self.__value = self.__func()
TypeError: 'NoneType' object is not callable
```

**Comment by iulianov** [comment]
I will not be able to get you much further than this but make the following change:
in unibuild/utility/lazy.py line 83
replace `if self.__value is None:`
with `if self.__value is None and self.__func is not None:`

Note: This change is purely debugging and just hides the real cause of why that task fails, although it does actually work if made.

I am currently working on getting "execute openssl_build_func" to succeed.

**Comment by TanninOne** [comment]
I just uploaded a couple of fixes, one includes a fix to the usvfs build and the one to lazy.

**Comment by AnyOldName3** [comment]
It might be an idea to add a slightly more verbose progress indicator to `run task "run init qt repository"` - I was left staring at it for several minutes, with no idea if I was stuck in an infinite loop or not.

Also, it now fails on Sip, and looks to me to **not** be the same issue as issue six: https://github.com/TanninOne/modorganizer-umbrella/issues/6

My data:

```
2016-01-09 00:02:27,944 run task "sip configure"
2016-01-09 00:02:27,957 failed to run sip configure.py (returncode 1), see .\build\sip-4.16.9\stdout.log and .\build\sip-4.16.9\stderr.log
2016-01-09 00:02:27,957 task sip configure failed
```

Stderr.log:

```
'"<function <lambda> at 0x0385E970>"' is not recognized as an internal or external command,
operable program or batch file.
```

Stdout.log is blank, though.

Either way, while I'm in the presence of people who are competent, would anyone mind telling me the command to revert all of my changes to a local copy of a git repository back to what they were originally, and then update everything to match the latest commits to the repository? So far my workflow has just been to delete everything and clone it again, which is cumbersome.

**Comment by iulianov** [comment]
If you did not make any commits to your local repository then you can just do a `git checkout -f master`.
This will undo all changes to staged and unstaged files (but not untracked ones). Then you can go ahead and either `git pull` if you cloned from this repo or do a `git fetch <upstream>` `git merge <upstream>/master` if you forked this repo.

**Comment by AnyOldName3** [comment]
Thanks very much.

**Comment by TanninOne** [comment]
Please try if the attached patch fixes the sip bug. The lambda mentioned in the error is the lambda in config['paths']['python']. This patch wraps that lambda in a Lazy object and has it evaluated when necessary.
[python_fix.zip](https://github.com/TanninOne/modorganizer-umbrella/files/83621/python_fix.zip)

**Comment by AnyOldName3** [comment]
Once I figured out how to apply a .patch, I set it off running. It was going well, but has been on `run task "execute openssl_build_func"` for thirty-five minutes on a pretty powerful PC. I'd assume it was just taking a while, except it doesn't seem to be using any CPU, memory, disk or network.

**Comment by iulianov** [comment]
That should take at most a minute. When I ran it last it popped up a message asking me if I want to allow it to make changes to my computer (the regular message windows asks when you run an installer). You can also check if you have the `<destination path>\build\Win64OpenSSL-1_0_2e` directory.

**Comment by AnyOldName3** [comment]
I have that directory, but it's empty. I guessed I'd be nagged by UAC, so I ran the command prompt as admin, so it would never have needed to ask me for permissions.

**Comment by AnyOldName3** [comment]
However, now I've restarted unimake.py, there does seem to be a folder with that name in the downloads directory, which may mean it's working now.

**Comment by iulianov** [comment]
ahh, that might mean you are using a relative path for the -d parameter to unimake.
The current build system does not work with relative paths - you need to give a full path.

**Comment by AnyOldName3** [comment]
It's still taking a while. The python file for this task is supposed to timeout after 15 seconds, but I'm guessing it isn't looking for the files in `<destination path>\downloads\build\Win64OpenSSL-1_0_2e`. If I'm guessing correctly, the python is passing an argument `/DIR=<destination path>` to the OpenSSL executable (which I'm guessing is just a self-extracting archive), but it's ignoring that argument.

**Comment by AnyOldName3** [comment]
I'm just running unimake with no arguments as I want it to put everything where it is.

**Comment by AnyOldName3** [comment]
Everything up to now has been fine with that.

**Comment by AnyOldName3** [comment]
If it doesn't support relative paths, that's unfortunate, as it looks like it uses `.` as the default parameter for `-d` if none is specified.

**Comment by AnyOldName3** [comment]
It does successfully pass that part if I manually type the current directory path. Maybe the script should be adjusted so it uses the output of `cd`

**Comment by AnyOldName3** [comment]
instead of `.` if no argument is passed for `-d`.

**Comment by AnyOldName3** [comment]
However, it's now aborting at this point:

```
2016-01-11 02:23:28,191 run task "run Tools/buildbot/external-common.bat"
2016-01-11 02:23:28,193 failed to run Tools\buildbot\external-common.bat (returncode 1), see C:\ModOrganizerDev\build\Python-2.7.11\stdout.log and C:\ModOrganizerDev\build\Python-2.7.11\stderr.log
2016-01-11 02:23:28,193 task run Tools/buildbot/external-common.bat failed
```

The stderr contains:

```
'Tools\buildbot\external-common.bat' is not recognized as an internal or external command,
operable program or batch file.
```

so I'll investigate that...

**Comment by AnyOldName3** [comment]
Well in build\python-2.7.11\tools\buildbot there's a batch file called external.bat and another called external-amd64.bat, but no external-common.bat. I see this as a likely candidate for the cause.

**Comment by iulianov** [comment]
Yeah, for Tools\buildbot\external-common.bat was deprecated in 2.7.11. You need to use PCBuild\get_externals.bat.
It might make more sense to build python manually at the moment since even if you get the external dependencies downloaded there are still issues with the build and as Tannin wrote in https://github.com/TanninOne/modorganizer-umbrella/issues/6#issuecomment-170225517 python can be built through the ide.

**Comment by AnyOldName3** [comment]
I built python (I think - I opened the PCbuild solution file, selected all the subprojects, and chose build) but there were quite a few errors and nine warnings (from tk, _tkinter and tix), then forced unimake to skip over the bit that failed by creating a dummy batch file for it to call. It now fails on `run task "cmake edit modorganizer-installer_bundle"` with the following in stderr.log:

```
CMake Error at CMakeLists.txt:13 (GET_FILENAME_COMPONENT):
  get_filename_component called with incorrect number of arguments


CMake Error at src/CMakeLists.txt:14 (FIND_PACKAGE):
  By not providing "FindQt5Widgets.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "Qt5Widgets", but CMake did not find one.

  Could not find a package configuration file provided by "Qt5Widgets" with
  any of the following names:

    Qt5WidgetsConfig.cmake
    qt5widgets-config.cmake

  Add the installation prefix of "Qt5Widgets" to CMAKE_PREFIX_PATH or set
  "Qt5Widgets_DIR" to a directory containing one of the above files.  If
  "Qt5Widgets" provides a separate development package or SDK, be sure it has
  been installed.



```

I'm guessing either things are being built in the wrong order, or a CMake variable wasn't set correctly.

**Comment by LePresidente** [comment]
This was fixed by turning ide_projects to false, will reopen if we decide to use that functionality again.
