### ISSUE TITLE
CMake cannot find boost libraries (dependecy_dir seems off)

### ISSUE THREAD

**Issue by iulianov** [TanninOne/modorganizer-umbrella#12]
I am having an issue where `DEPENDENCIES_DIR` is being set incorrectly in makefile.uni.py.
The code sets it to `config["__build_base_path"]/build` which in turn is set in unimake.py to `args.destination`.
When I run `python unimake.py -d output` the `DEPENDENCIES_DIR` is set to `output/build` and that is then appended to the working directory of cMake which is not the working directory of unimake.
This causes the cMake to not find the boost, python and qt libraries among others.

As an example for the build of 'modorganizer':
unimake cwd = `f:/projects/umbrella`
cMake cwd = `f:/projects/umbrella/output/build/modorganizer_super/modorganizer`
`DEPENDENCIES_DIR` = `f:/projects/umbrella/output/build/modorganizer_super/modorganizer/output/build`
Where dependecies actually live = `f:/projects/umbrella/output/build/`

I changed the code in unimake.py to wrap the output directory inside an `os.path.abspath` call but I am not sure if there is some root problem that I am missing here.

**Comment by TanninOne** [comment]
yeah, that's probably it. I always use absolute paths for the destination so I didn't notice. Would you mind submitting a pull request?

**Comment by LePresidente** [comment]
This doesn't occur anymore after merge, closing
