### ISSUE TITLE
Loot api is outdated

### ISSUE THREAD

**Issue by iulianov** [TanninOne/modorganizer-umbrella#14]
The loot api that is specified in makefile.uni.py is 0.8.0 but it does not contain the code for fallout 4. A manual download of the latest snapshot is required for modorganizer-lootcli to compile.

**Comment by LePresidente** [comment]
Waiting on someone to fix modorganizer-lootcli to work with 0.10.1 then will close this.

**Comment by LePresidente** [comment]
Closing due to this has been fixed.
