### ISSUE TITLE
Default paths in config.py

### ISSUE THREAD

**Issue by ThosRTanner** [TanninOne/modorganizer-umbrella#2]
I installed graphviz and by default dot ends up in "C:/Program Files (x86)/Graphviz2.38/bin/dot.exe". I think config.py might need to be in .gitignore and something else should be supplied which gets copied if no other file is supplied.

**Comment by TanninOne** [comment]
The graphviz stuff is a toy anyway. It's useful to debug the build system while I develop it but there is no reason it should require graphviz once it runs reasonably well.
I want the build to just work out of the box as long as dependencies are fulfilled.

**Comment by GrantSP** [comment]
That being the case, what then are the absolute necessities for a successful build?

**Comment by ThosRTanner** [comment]
Which reminds me. Are you still supporting 'installerBatch' and 'installerBCF'? I can't find them on Github (admittedly I might well be looking in the wrong place)

**Comment by TanninOne** [comment]
@GrantSP Afaik what you need is the tools referenced in the config with the exception of graphviz which is optional now: cmake, svn, git, perl, ruby, python, visual studio.

Currently the umbrella builds python and qt, both big projects. These builds are only necessary for preparing releases so I will probably add the option later to use binary builds instead, that should eliminate the need for svn, perl and ruby.

I try to autodownload non-standard python modules through the **init**.py though I may be missing some. If you get error messages about missing modules, please let me know.

@ThosRTanner Those projects were never used. installerBCF contains practically no code so there is little point importing it. installerBatch was only kept as sample code. I haven't included the other sample plugin (helloWorldCpp) hasn't been imported yet either.
I'll probably create a "samples" repository but first I'd like to get everything else up and running.
