### ISSUE TITLE
HTTP 404 error when downloading zlib 1.2.8

### ISSUE THREAD

**Issue by fireundubh** [TanninOne/modorganizer-umbrella#32]
Zlib has been updated to 1.2.9.

* Old: [http://zlib.net/zlib-1.2.8.tar.gz](http://zlib.net/zlib-1.2.8.tar.gz) [No longer works.]
* New: [http://zlib.net/zlib-1.2.9.tar.gz](http://zlib.net/zlib-1.2.9.tar.gz)

`zlib_version` in `unibuild/projects/zlib.py` should be `'1.2.9'` now, if the project builds with that version.

**Comment by LePresidente** [comment]
1.2.10 now sigh, gonna wait to see if it slows down, or will need to find a mirror.

**Comment by LePresidente** [comment]
Should be fixed. Reopen if reoccurs.
