### ISSUE TITLE
Out of date link for zlib, openssl, ....

### ISSUE THREAD

**Issue by Holt59** [TanninOne/modorganizer-umbrella#38]
I tried a simple build using:

```
python unimake.py -d ..\base
```

But I get 404 errors from `urllib2` when trying to download some of the projects, so far:

- `zlib`
- `openssl`

**Comment by Holt59** [comment]
Quick fix:

- `zlib` (`unbuild/projects/zlib.py`), change `1.2.8` to `1.2.11`.
- `openssl` (`unbuild/projects/openssl.py`), change `1.0.2j` by `1.1.0f`.

**Comment by LePresidente** [comment]
I pushed all my changes from my repo here as well which already addressed this issue

**Comment by Holt59** [comment]
@LePresidente Did not see you had your own umbrella project - Should I still be using this one or should I completely switch to your repositories?

**Comment by LePresidente** [comment]
@Holt59 

My latest push to this repo will checkout all my repos, You should probably start a fresh and make sure your path is not to long e.g unimake.py -d "F:/Build"

**Comment by Holt59** [comment]
@LePresidente I did understand that part, but there are actually two repositories for each of the projects, yours and @TanninOne repositories.

If I plan to contribute, I would like to know on which one should I open pull-request?

@TanninOne repositories seem to be outdated and neglected, but you still made a push-request to this repository instead of just asking me to use yours, so I am just trying to understand the way you work with @TanninOne to be able to contribute properly.

**Comment by LePresidente** [comment]
@Holt59, Use mine then, Though I'm currently not working on it at this moment. If i decide to stop working on it completely I will push everything to @TanninOne  repositories.

Use my issue logs as well (https://github.com/LePresidente/modorganizer), Since they are more active and relevant to V2 only
