### ISSUE TITLE
Non-ASCII character & bad indentation

### ISSUE THREAD

**Issue by BrysonZimmerman** [TanninOne/modorganizer-umbrella#8]
https://github.com/TanninOne/modorganizer-umbrella/blob/bc8e0d9a45c33ea7d1e89f1b43055bdef47bdaca/unibuild/modules/build.py#L117

Non ASCII character at the end of this line.

https://github.com/TanninOne/modorganizer-umbrella/blob/master/unibuild/modules/urldownload.py#L123

This exception block causes indentation errors afterward

**Comment by TanninOne** [comment]
You're right, that was committed accidentally. But why don't you just submit a patch/pull request?

**Comment by BrysonZimmerman** [comment]
@TanninOne I can't get Umbrella to work. I don't want to submit anything that might break the code further. My Python skills are terribad, also.

**Comment by TanninOne** [comment]
Well, you cant commit to the main repository anyway, you would only submit a patch (or even better: a pull request) which I would check before merging. This is not to say you should submit tons of untested changes but you also don't have to be overly careful.
